### ISSUE TITLE
Replacing token with environment variable not working

### ISSUE THREAD

**Issue by sandeep-tembare-ceataec** [qetza/replacetokens#15]
I have been trying to replace tokens in the file with the help of environment variables. Tokens are replaced with blank values.

As per README, tried using `--variables '$VARS'` to replace tokens with values from environment variables.

Logs:
![image](https://github.com/qetza/replacetokens/assets/155625684/cf90b90c-b7eb-46df-9a89-cd504b7fc5f9)

**Comment by sandeep-tembare-ceataec** [comment]
Setting the following environment variables works
VARS='{"USER":"Sandeep"}'

**Comment by qetza** [comment]
Hi @sandeep-tembare-ceataec,
Another option is to set the variables as JSON directly in the command line :

```sh
replacetokens --sources terraform.tfvars.json --variables "{ \"USER\": \"$USER\" }"
```

**Comment by sandeep-tembare-ceataec** [comment]
Hi @qetza,

It would be great if the task considers environment variables by default, similar to the azure devops task. Just a suggestion :) 
`replacetokens --sources terraform.tfvars.json`

However, we found work around to pass environment variables in json and it works,
`replacetokens --sources terraform.tfvars.json --variables "$(jq -n env)"`

Anyways thanks for the task ;)

**Comment by qetza** [comment]
Hi @sandeep-tembare-ceataec,
Thanks for the suggestion, i'll add in the next release a new parameter `--use-env` so that it will automatically initialize variables with env variables and then override with or add variables specified in the `--variables` parameter (which will become mandatory on if `--use-env` is not specified)

**Comment by qetza** [comment]
Hi @sandeep-tembare-ceataec,
Version 1.7.0 of the CLI now support the `--use-env` parameter to load env variables.

You can now simply use:
```sh
replacetokens --sources terraform.tfvars.json --use-env
```
